server:
  port: 12000

spring:
  application:
    name: inventory
  profiles:
    active: dev
  rabbitmq:
    host: ${VM.host}
    port: 5672
    virtual-host: /
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  datasource:
    username: root
    password: ${mysql.password}
    url: ${mysql.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
      - 'consul:'
      - 'optional:classpath:application-shared.yml'
  cloud:
    consul:
      host: ${VM.host}
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-interval: 10s
      config:
        enabled: true
        profile-separator: '-'
        format: yaml
        default-context:
          - global
          - inventory
        prefixes: config


