server:
  port: 88

spring:
  config:
    import:
      - 'consul:'
      - 'optional:classpath:application-shared.yml'
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
        - id: admin
          uri: lb://renren-fast
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*), /renren-fast/${segment}
    consul:
      host: ${VM.host}
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-interval: 10s
      config:
        enabled: true
        profile-separator: '-'
        format: yaml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
