server:
  port: 9000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.30.103.222:3307/mall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "consul:"
  application:
    name: coupon
    cloud:
      consul:
        default-context: coupon
        host: localhost
        port: 8500
        discovery:
          service-name: ${spring.application.name}
          prefer-ip-address: true
          health-check-interval: 10s
        config:
          enabled: true
          profile-separator: '-'
          format: yaml

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
